server:
  port: 8888  # Config Server runs on port 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shiva909/movie-config-repo.git  # Replace with your actual repo
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          clone-on-start: true  # Ensures latest changes are fetched on startup
