spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable service discovery in API Gateway Must & Should
      routes:
        - id: movie-service
          uri: lb://movieservice
          predicates:
            - Path=/movies/**
        - id: theatre-service
          uri: lb://theaterservice
          predicates:
            - Path=/theatres/**
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/users/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Your Eureka server URL

server:
  port: 8080  # This is the port for the API Gateway
